Feature/heewon/connect celery worker
ainize-team/ServingLLMFastCelery pull request #3
Opened 2022-07-29 06:43 UTC by godhw

[LLM-Worker]("https://github.com/ainize-team/LLM-Worker")와 함께 작동하는 FastAPI server입니다. 의존성 때문에 같이 파일에 넣어두었고, FastAPI, Celery 각각 docker에 띄울 수 있습니다.

2022-07-29 07:12 UTC, jujeongho0 submitted a review, later dismissed

2022-07-29 07:39 UTC, 589hero commented on README.md
> +sudo docker run --name redis -d -p 6379:6379 redis
```sudo```는 삭제해야 될 것 같습니다.

2022-07-29 07:58 UTC, byeongal requested changes

2022-07-29 07:58 UTC, byeongal commented on requirements-dev.txt
> +--find-links https://download.pytorch.org/whl/torch_stable.html
celery 와 fastapi dev 분리 해주세요.

2022-07-29 07:58 UTC, byeongal commented on requirements.txt
> +--find-links https://download.pytorch.org/whl/torch_stable.html
해당 파일이 만약 필요 없다면 지워 주세요.

2022-07-29 07:58 UTC, byeongal commented on requirements-fastapi.txt
> +accelerate==0.10.0
fastapi 에서 필요없다면 지워 주세요.

2022-07-29 07:58 UTC, byeongal commented on requirements-fastapi.txt
> +transformers==4.20.1
ditto

2022-07-29 07:58 UTC, byeongal commented on src/api/configs/config.py
> +    APP_NAME: str = "Fast API Server"
pydantic 에서 settings 를 만들 때 snake_case 를 사용하는 것 같습니다.

https://pydantic-docs.helpmanual.io/usage/settings/

2022-07-29 07:58 UTC, byeongal commented on src/api/payloads/response.py
> +    status: str = ResponseStatusEnum.PENDING.value
status 에 `ResponseStatus` 가 될 수 없는 값이 올 수 없도록 `str` 에서 `ResponseStatusEnum` 로 값 수정 부탁 드려요

2022-07-29 07:58 UTC, byeongal commented on src/api/router/prediction.py
> +    if not check:
이 경우에 대한 Response를 정의해주세요.
ex) assigned

2022-07-29 08:30 UTC, jikerbug approved these changes, later dismissed
LGTM

2022-07-29 08:32 UTC, 589hero commented on src/api/configs/config.py
> +from pydantic import BaseSettings
```configs```디렉토리를 없애고 ```config.py```로 빼는건 어떨까요?

2022-07-29 09:01 UTC, godhw commented on requirements-fastapi.txt
> +transformers==4.20.1
없으면 dockerize가 되지 않습니다..

2022-07-29 09:01 UTC, 589hero commented on src/api/configs/config.py
> +
```./src/celery_tasks```도 ```configs```디렉토리를 없애고 ```config.py```로 빼는건 어떨까요?

2022-07-29 09:02 UTC, godhw commented on requirements-fastapi.txt
> +accelerate==0.10.0
없으면 torch를 설치해야 합니다..

2022-07-29 09:41 UTC, godhw commented on README.md
> +sudo docker run --name redis -d -p 6379:6379 redis
해결했습니다!

2022-07-29 09:41 UTC, godhw commented on requirements-dev.txt
> +--find-links https://download.pytorch.org/whl/torch_stable.html
해결했습니다!

2022-07-29 09:41 UTC, godhw commented on requirements.txt
> +--find-links https://download.pytorch.org/whl/torch_stable.html
해결했습니다!

2022-07-29 09:42 UTC, godhw commented on requirements-fastapi.txt
> +accelerate==0.10.0
torch 설치로 변경했습니다

2022-07-29 09:42 UTC, godhw commented on src/api/configs/config.py
> +    APP_NAME: str = "Fast API Server"
해결했습니다!

2022-07-29 09:42 UTC, godhw commented on src/api/payloads/response.py
> +    status: str = ResponseStatusEnum.PENDING.value
해결했습니다!

2022-07-29 09:42 UTC, godhw commented on src/api/router/prediction.py
> +    if not check:
해결했습니다!

2022-07-29 09:42 UTC, godhw commented on src/api/configs/config.py
> +from pydantic import BaseSettings
해결했습니다!

2022-07-29 09:42 UTC, godhw commented on src/api/configs/config.py
> +
해결했습니다!

2022-07-29 09:46 UTC, 589hero submitted a review, later dismissed
LGTM

2022-07-29 10:03 UTC, 589hero approved these changes
LGTM

2022-08-02 03:33 UTC, byeongal approved these changes
LGTM!

2022-08-02 03:36 UTC, merged