Feature/heewon/separate worker api
ainize-team/ServingLLMFastCelery pull request #7
Opened 2022-08-04 02:23 UTC by godhw

Fast API만 분리했습니다. Celery는 LLM-Worker repo로 올리겠습니다. README도 꼭 확인해주세요!

2022-08-04 02:29 UTC, jujeongho0 approved these changes, later dismissed

2022-08-04 02:29 UTC, byeongal requested changes

2022-08-04 02:29 UTC, byeongal commented on src/api/enums.py
>  class EnvEnum(Enum):
Enum->StrEnum

2022-08-04 02:29 UTC, byeongal commented on src/api/payloads/response.py
> +    status: str = ResponseStatusEnum.PENDING
str->ResponseStatusEnum

2022-08-04 02:29 UTC, byeongal commented on src/api/router/prediction.py
> +    data = json.loads(data)
Q) data 의 타입이 `Dict` 인데 `json.lodas` 하는 이유가 있을까요?

2022-08-04 02:34 UTC, 589hero commented on src/api/config.py
worker없이 fastapi만 있으므로 디렉토리를 ```src/api```에서 ```src```를 없애고 ```api```만 하면 좋을 것 같습니다

2022-08-04 02:34 UTC, 589hero commented on Dockerfile
```fastapi_start.sh```는 worker와 fastapi 모두 있을 때 이를 구분하려고 한 거여서 ```start.sh```로 이름을 바꿔도 좋을 것 같습니다!

2022-08-04 02:52 UTC, godhw commented on src/api/enums.py
>  class EnvEnum(Enum):
수정했습니다!

2022-08-04 02:52 UTC, godhw commented on src/api/payloads/response.py
> +    status: str = ResponseStatusEnum.PENDING
수정했습니다!

2022-08-04 02:53 UTC, godhw commented on src/api/router/prediction.py
> +    data = json.loads(data)
Dict가 아닐 경우가 있어 어노테이션 삭제했습니다!

2022-08-04 03:02 UTC, godhw commented on src/api/config.py
수정했습니다!

2022-08-04 03:03 UTC, godhw commented on Dockerfile
수정했습니다! 그리고 관련해서 질문이 있는데, start.sh가 컨테이너의 app/start.sh가 아닌 ./srart.sh에 있어도 될까요?

2022-08-04 03:11 UTC, 589hero commented on Dockerfile
FastAPI에서 8000번 포트를 사용하므로 ```EXPOSE 8000```으로 바꿔야 될 것 같습니다.

2022-08-04 03:39 UTC, godhw commented on Dockerfile
수정했습니다!

2022-08-04 03:45 UTC, 589hero commented on api/config.py
> +    redis_port: int = 6379
Pydantic Field를 이용해서 ```redis_port```의 범위를 ```0~65535```로 설정하면 어떨까요?

2022-08-04 03:45 UTC, 589hero commented on api/config.py
> +    redis_db: int = 0
ditto

2022-08-04 03:46 UTC, 589hero commented on api/config.py
> +    redis_port: int = 6379
Pydantic Field에 ```description```도 넣으면 좋을 것 같습니다.

2022-08-04 03:46 UTC, 589hero commented on api/config.py
> +    backend_uri: str = "setup"
setup이 무슨 뜻인가요?

2022-08-04 03:54 UTC, 589hero approved these changes, later dismissed
LGTM

2022-08-04 03:58 UTC, byeongal commented on Dockerfile
> +COPY ./requirements.txt ./requirements.txt
minor) 
```
WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./src/ app/
```
으로 변경하는 것이 좋을 것 같습니다. 지금 구조에서는 코드 수정이 발생하면 buiild 시간이 오래 걸릴 것 같습니다.

2022-08-04 04:05 UTC, godhw commented on Dockerfile
> +COPY ./requirements.txt ./requirements.txt
넵 추가적으로 src가 없는데 src를 옮기는 것으로 돼있어서 그것도 수정하겠습니다!

2022-08-04 04:08 UTC, jikerbug commented
LGTM

2022-08-04 04:13 UTC, godhw commented on api/config.py
> +    redis_port: int = 6379
수정했습니다!

2022-08-04 04:13 UTC, godhw commented on api/config.py
> +    redis_db: int = 0
수정했습니다!

2022-08-04 04:13 UTC, godhw commented on api/config.py
> +    backend_uri: str = "setup"
임시로 적어둔 것인데 auto generate로 수정했습니다

2022-08-04 04:23 UTC, 589hero commented on api/router/prediction.py
> +        raise HTTPException(data["status_code"], data["message"])
43번째 라인과 마찬가지로 ```raise HTTPException(status_code=data["status_code"], detail=data["message"])```로 바꿔서 형태를 맞추는건 어떨까요?

2022-08-04 04:26 UTC, godhw commented on api/router/prediction.py
> +        raise HTTPException(data["status_code"], data["message"])
수정했습니다!

2022-08-04 04:27 UTC, 589hero approved these changes
LGTM

2022-08-10 03:28 UTC, byeongal approved these changes
LGTM!

2022-08-10 03:33 UTC, jujeongho0 approved these changes

2022-08-10 04:58 UTC, jikerbug reviewed
LGTM!

2022-08-10 05:06 UTC, merged