Feature/youngjae/add poetry
ainize-team/ServingLLMFastCelery pull request #8
Opened 2022-08-22 04:32 UTC by byeongal

패키지 관리 도구를 poetry로 수정 하였습니다.

2022-08-22 05:28 UTC, godhw requested changes

2022-08-22 05:28 UTC, godhw commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
아래와 중복되는 것 같습니다.

2022-08-22 05:28 UTC, godhw commented on Dockerfile
> +ENV PYTHONUNBUFFERED 1
ditto

2022-08-22 08:56 UTC, byeongal commented on Dockerfile
> +ENV PYTHONUNBUFFERED 1
수정 했습니다.

2022-08-23 01:20 UTC, godhw approved these changes, later dismissed
LGTM

2022-08-23 01:36 UTC, 589hero commented on Dockerfile
> -COPY ./requirements.txt ./requirements.txt
poetry를 사용하면 ```requirements.txt```, ```requirements-dev.txt```파일은 삭제해도 되지 않나요?

2022-08-23 01:39 UTC, byeongal commented on Dockerfile
> -COPY ./requirements.txt ./requirements.txt
수정했습니다.

2022-08-23 05:26 UTC, 589hero approved these changes
LGTM

2022-08-23 06:01 UTC, godhw approved these changes

2022-08-23 06:07 UTC, merged